### ISSUE TITLE
Error with dataview javascript

### ISSUE THREAD

**Issue by jradburn** [chhoumann/DemoVault#6]
When implementing the macro
![Screenshot_2](https://user-images.githubusercontent.com/113862813/190929795-a94b71e5-8abe-4185-8c19-8de5e5601f4b.png)
 and template I get this error when the file has been created.

**Comment by Sahorri** [comment]
Hello,
I have the same issue.
Can you help me ?
I cannot figure out what's wrong with this.
Thanks a lot :)

**Comment by chhoumann** [comment]
Hi @jradburn 

This means the file isn't found, i.e. the file doesn't seem to exist according to dataview.
Could the file have other naming than `2022-09-18 - tr`?

**Comment by aeciolevy** [comment]
Hi @chhoumann 
I am getting the same error.
The file is defined, I went to debug and the problem happen on the `dv.list` call
<img width="470" alt="Screenshot 2023-03-26 at 5 47 08 AM" src="https://user-images.githubusercontent.com/16165803/227767763-f8e7af29-220e-443d-bb8c-186f85d45257.png">

I am debugging and to be honest, I don't know much about Dataview, but the problem is with this `dv` object and the component which is null, so it cannot add the `dv.span` in the end of the list.
<img width="303" alt="Screenshot 2023-03-26 at 5 46 47 AM" src="https://user-images.githubusercontent.com/16165803/227767744-bf445374-f29e-4b47-90e6-4d1d5e020f02.png">

Somehow none of Dataview InlineJS queries are working.
I am using the autotracking_goal_item_template.

**Comment by chhoumann** [comment]
**An update to others who might have this issue:**
Looks like it's due to file name inconsistencies.

If you wish to change any of the file names, please ensure you do so in all places. This includes in the Dataview scripts inside the templates.
