### ISSUE TITLE
Typo in "Configuring Add Goal" section of tutorial "How I Manage Projects and Goals in Obsidian"; mixes up file path for goals & projects

### ISSUE THREAD

**Issue by Philogicatician** [chhoumann/DemoVault#9]
Hello, just wanted to point out a typo in Christian's wonderful tutorial [How I Manage Projects and Goals in Obsidian](https://bagerbach.com/blog/projects-and-goals-obsidian).

It's under the "Configuring Add Goal".

It states,
> You should configure it such that
> - The template path points to the template we inserted for _**projects**_

Which isn't what the path should point to; it should point to `path/to/goal_item_template.md`.

Here's a screen shot of the larger context of that section:
![image](https://user-images.githubusercontent.com/9929287/199660357-49961b76-70c4-46d1-9ed6-563de981581c.png)

Later on, there _is_ a screenshot that correctly demonstrates the file path shown here:
![image](https://user-images.githubusercontent.com/9929287/199661540-a24d49b0-3110-41ec-a84f-cc86e866e3bc.png)

However, people may take a while to catch this error or mistakenly assume some of the plugins or integration is buggy, so I wanted to point it out.  Especially if someone doesn't have a tech background, they could get easily discouraged if they don't catch this misstep.

In any case, great job to @chhoumann for developing QuickAdd & MetaEdit and coming up with a system for goal & project management in Obsidian.  👏👏👏  Never thought such a thing could be done (without the tedium of editing the meta data constantly).

**Comment by chhoumann** [comment]
Hi @Philogicatician, thank you very much!

Should be fixed to say `goal` instead of `project` now. Absolutely agreed that these mistakes can lead to frustration, so super glad you pointed it out!

Hope you find the system & my plugins useful. :)

**Comment by Philogicatician** [comment]
Sure thing, @chhoumann! ^.^  Finished your tutorial How to use [QuickAdd for Obsidian - with examples](https://youtu.be/gYK3VDQsZJo) which just led me to your blog.  My JS-foo is weak, but you've given me inspiration to improve it ✊  

Relatedly, any tips on a newcomer to JS?  I was looking at Next & Nuxt a while back for building some front-end dev chops, but never really committed to anything (got lost in the lure of "Let me research all the pros & cons so I don't have to deal with a refactoring nightmare..." and then other things fell on my plate)

For context, my undergrad experience was C++ for my comp sci minor (major was pure/abstract math).  My personal interests led me to Julia & Python (mainly because of TDA & data sci).  I can usually grasp theory & abstractions relatively quickly (or at least, thoroughly), but I lack the experience of real software devs (what the tradeoffs are between certain design choices, what warrants the use of a particular tech stack over another, etc)  

Most of my programming experience is just me tinkering around to see how stuff works on a conceptual & practical level (eg, how does the language achieve this outcome? what does the machine/hardware _actually_ do when given these instructions?) or solving puzzles (Leetcode, HackerRank, etc)

Anywho, thanks again for sparking some interest in more practical stuff 🙏

**Comment by chhoumann** [comment]
That's awesome, @Philogicatician! Learning JS is a superpower.

I personally favor Next.js, which is what I've built my personal blog with. I've also used Astro for my [notes page](https://notes.bagerbach.com), which was a great experience as well.

I think doing CodeWars and similar is decent, but even better is just building stuff. 
Especially if you're solving problems you have. That's what most of my plugins & workflows come from. They all started small, but eventually grew.

- [Javascript.info](https://javascript.info) is a great resource, but don't get stuck in 'tutorial-hell'. Just start building and learn from there.
- Using JavaScript is good, but it's actually harder than just learning TypeScript and using that.
- If you want to do Obsidian-specific stuff, read plugin source code (& [plugin docs from Marcus](https://marcus.se.net/obsidian-plugin-docs/)). Seriously a big help. Find plugins that have solved problems you have / want to improve upon, and either contribute or make a personal script.

Most of my learning has just been: build → find problem → find solution → repeat.
It's not that tutorials are a complete waste of time, because they can be great for learning best practices, getting the big picture, etc. I've just found that building is a faster learning loop. :)
